### ISSUE TITLE
Invert setting?

### ISSUE THREAD

**Issue by agmlego** [Sil3ntStorm/factorio-filter-combinator#2]
Is there a way to make these invert the filter settings, so that they pass only the signals that do not match?

**Comment by Sil3ntStorm** [comment]
Not currently.
I can check at some point if I can do that easily, but it will probably be a separate entity (a "Blacklist Filter Combinator" or similar), as all the logic is actual circuit logic and not done in code.
Currently busy with other projects, so it will be some time before I can look into it.
