### ISSUE TITLE
Error while applying migration: Filter Combinator: 0.1.0.lua

### ISSUE THREAD

**Issue by MikdadAgasiev** [Sil3ntStorm/factorio-filter-combinator#7]
Error while applying migration: Filter Combinator: 0.1.0.lua

LuaGameScript doesn't contain key active_mods.
stack traceback:
	[C]: in function '__index'
	__silent-filter-combinator__/migrations/0.1.0.lua:7: in main chunk

**Comment by Sil3ntStorm** [comment]
How do you even get that error? I have started numerous saves with the version and never had this issue?

**Comment by Sil3ntStorm** [comment]
Fixed with 43725c4
